export const violations_count = [
  {
    id: 1,
    worker: {
      name: "Blaise DEFLOO",
      img: "./blaise.png",
      position: "Manager",
      company: "./biowanze.png",
    },
    protective_gloves: 2,
    safety_glasses: 0,
    ear_protection: 0,
    mask_protection: 10,
    knee_pads: 0,
    safety_shoes: 0,
    coverall: 1,
    hivis_jackets: 0,
    safety_harness: 0,
    face_shield: 3,
    hard_hat: 0,
    welding_helmet: 0,
  },
  {
    id: 2,
    worker: {
      name: "Blaise DEFLOO",
      img: "./blaise.png",
      position: "Manager",
      company: "./biowanze.png",
    },
    protective_gloves: 0,
    safety_glasses: 2,
    ear_protection: 0,
    mask_protection: 0,
    knee_pads: 0,
    safety_shoes: 10,
    coverall: 0,
    hivis_jackets: 1,
    safety_harness: 0,
    face_shield: 0,
    hard_hat: 0,
    welding_helmet: 3,
  },
  {
    id: 3,
    worker: {
      name: "Blaise DEFLOO",
      img: "./blaise.png",
      position: "Manager",
      company: "./biowanze.png",
    },
    protective_gloves: 2,
    safety_glasses: 0,
    ear_protection: 0,
    mask_protection: 10,
    knee_pads: 0,
    safety_shoes: 0,
    coverall: 1,
    hivis_jackets: 0,
    safety_harness: 0,
    face_shield: 3,
    hard_hat: 0,
    welding_helmet: 0,
  },
  {
    id: 4,
    worker: {
      name: "Blaise DEFLOO",
      img: "./blaise.png",
      position: "Manager",
      company: "./biowanze.png",
    },
    protective_gloves: 0,
    safety_glasses: 2,
    ear_protection: 12,
    mask_protection: 3,
    knee_pads: 1,
    safety_shoes: 0,
    coverall: 0,
    hivis_jackets: 0,
    safety_harness: 3,
    face_shield: 0,
    hard_hat: 0,
    welding_helmet: 13,
  },
  {
    id: 5,
    worker: {
      name: "Blaise DEFLOO",
      img: "./blaise.png",
      position: "Manager",
      company: "./biowanze.png",
    },
    protective_gloves: 0,
    safety_glasses: 2,
    ear_protection: 0,
    mask_protection: 0,
    knee_pads: 0,
    safety_shoes: 10,
    coverall: 0,
    hivis_jackets: 1,
    safety_harness: 0,
    face_shield: 0,
    hard_hat: 0,
    welding_helmet: 3,
  },
  {
    id: 6,
    worker: {
      name: "Blaise DEFLOO",
      img: "./blaise.png",
      position: "Manager",
      company: "./biowanze.png",
    },
    protective_gloves: 0,
    safety_glasses: 0,
    ear_protection: 4,
    mask_protection: 0,
    knee_pads: 0,
    safety_shoes: 0,
    coverall: 0,
    hivis_jackets: 1,
    safety_harness: 2,
    face_shield: 15,
    hard_hat: 1,
    welding_helmet: 0,
  },
  {
    id: 7,
    worker: {
      name: "Blaise DEFLOO",
      img: "./blaise.png",
      position: "Manager",
      company: "./biowanze.png",
    },
    protective_gloves: 0,
    safety_glasses: 2,
    ear_protection: 4,
    mask_protection: 1,
    knee_pads: 0,
    safety_shoes: 6,
    coverall: 0,
    hivis_jackets: 0,
    safety_harness: 0,
    face_shield: 4,
    hard_hat: 0,
    welding_helmet: 2,
  },
];
